server:
  port: 8083
urls:
  account-service: http://localhost:8080/account
  classifier-service: http://localhost:8082/classifier
reports-storage-path: C:\projects\Finance
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/report
    username: postgres
    password: 111
  mvc:
    view:
      prefix: /views/
      suffix: .jsp